import ArrowDropDown from "@/shared/assets/arrow-drop-down.svg";
import CancelSVG from "@/shared/assets/cancel.svg";
import CheckboxOutline from "@/shared/assets/check-box-outline.svg";
import Checkbox from "@/shared/assets/check-box.svg";
import CloseSvg from "@/shared/assets/close.svg";
import CommunitySVG from "@/shared/assets/community.svg";
import CompassSVG from "@/shared/assets/compass.svg";
import EditSvg from "@/shared/assets/edit.svg";
// svg 파일 Import
import EmailSvg from "@/shared/assets/email.svg";
import Indeterminate from "@/shared/assets/indeterminate.svg";
import LocationSVG from "@/shared/assets/location.svg";
import MapLocationSearching from "@/shared/assets/map-location-searching.svg";
import MapSVG from "@/shared/assets/map.svg";
import MyLocationSVG from "@/shared/assets/my-location.svg";
import NotificationSVG from "@/shared/assets/notification.svg";
import PinShadowSVG from "@/shared/assets/pin-shadow.svg";
import StartSVG from "@/shared/assets/start.svg";
import VisibilityOffSvg from "@/shared/assets/visibility-off.svg";
import VisibilityOnSvg from "@/shared/assets/visibility-on.svg";
import WardLeftSvg from "@/shared/assets/ward-left.svg";
import withIcon from "./Icon";

// Icon 컴포넌트 생성
export const EmailIcon = withIcon(EmailSvg);
export const VisibilityOnIcon = withIcon(VisibilityOnSvg);
export const VisibilityOffIcon = withIcon(VisibilityOffSvg);
export const WardLeftIcon = withIcon(WardLeftSvg);
export const CloseIcon = withIcon(CloseSvg);
export const EditIcon = withIcon(EditSvg);
export const CheckboxIcon = withIcon(Checkbox);
export const CheckboxOutlineIcon = withIcon(CheckboxOutline);
export const IndeterminateIcon = withIcon(Indeterminate);
export const MapLocationSearchingIcon = withIcon(MapLocationSearching);
export const ArrowDropDownIcon = withIcon(ArrowDropDown);
export const StartIcon = withIcon(StartSVG);
export const LocationIcon = withIcon(LocationSVG);
export const MyLocationIcon = withIcon(MyLocationSVG);
export const NotificationIcon = withIcon(NotificationSVG);
export const CompassIcon = withIcon(CompassSVG);
export const MapIcon = withIcon(MapSVG);
export const CommunityIcon = withIcon(CommunitySVG);
export const PinShadowIcon = withIcon(PinShadowSVG);
export const CancelIcon = withIcon(CancelSVG);
